### ISSUE TITLE
hpa-operator deletes HPAs that it does not manage

### ISSUE THREAD

**Issue by BenBlaisdell** [banzaicloud/hpa-operator#11]
I have multiple helm charts deployed that natively create HPAs. hpa-operator deletes these HPAs because their Deployments don't have the hpa-operator annotations.

**Comment by sancyx** [comment]
Yes originally, there was an assumption that in case you install hpa-operator you want to manage HPA objects through deployment annotations exclusively. We can create a new annotation like hpa.autoscaling.banzaicloud.io.managed=true/false to control hpa management, so that HPA operator will only delete HPA object annotated with hpa.autoscaling.banzaicloud.io.managed=false. Still in case you set up some HPA with the hpa-operator that will override original HPA if it's with same name, or even worse there will be 2 HPA objects in parallel, so you are not able to manage HPA objects created manually, but with this managed annotation we can avoid deleting manually created HPA's. Would this solution fine for you? @BenBlaisdell
