### ISSUE TITLE
Couldn't get resource list for custom.metrics.k8s.io/v1beta1

### ISSUE THREAD

**Issue by phpdave11** [banzaicloud/hpa-operator#17]
**Describe the bug**
I installed this chart with helm and attempted to add annotations to one of my deployments, and I am getting an ERROR when viewing hpa-operator logs.

**Steps to reproduce the issue:**

1) Install hpa-operator with helm
```sh
helm install hpa-operator banzaicloud-stable/hpa-operator
```

2) Add annotations to my deployment

3) View hpa-operator logs
```sh
kubectl logs -f -l app=hpa-operator-hpa-operator
```

Output: 
```sh
ERROR: logging before flag.Parse: E1129 23:05:56.295851       1 memcache.go:153] couldn't get resource list for custom.metrics.k8s.io/v1beta1: <nil>
ERROR: logging before flag.Parse: E1129 23:06:56.342624       1 memcache.go:153] couldn't get resource list for custom.metrics.k8s.io/v1beta1: <nil>
```

**Expected behavior**
Expected to not get that error message.

**Additional context**
Kubernetes 1.14 (Amazon EKS)
Helm 3.0.0
stable/metrics-server helm chart installed

**Comment by sancyx** [comment]
Hi @phpdave11 , this error appears in the log because you probably don't have any custom metrics and k8s client-go returns this error in of an empty list. This problem has been already fixed in client-go (https://github.com/kubernetes/kubernetes/pull/71190/files) so should be solve if we upgrade to a newer k8s version. 
Although this error look bad in the logs, this should not affect operator functionality, hpa resources should be created/updated. Did you checked they were not created?
Could you please attach the annotation you've attached to your deployment?

**Comment by phpdave11** [comment]
@sancyx thank you for the explanation.  The hpa-autoscaler seems to be working fine despite the error message.
