### ISSUE TITLE
[feat] Scale different StatefulSet instead of the main one

### ISSUE THREAD

**Issue by rimusz** [banzaicloud/hpa-operator#9]
First, thanks a lot for creating this operator, it really makes easier to set HPAs 👍 

I have an interesting use case, e.g. StatefulSets:
```
master - one replica
members - 0 replicas
```

When master has e.g. CPU load more than 70% instead of scaling master can the members be scaled, so instead of creating HPA for the watched sts, scale other specified sts?

**Comment by sancyx** [comment]
If I understand correctly you have two separate StatefulSets and you want to scale the 'members' sts depending on 'master' sts cpu value? Default cpu & memory metrics are watching only for metrics of targeted pods, however you can complete your use case using custom metrics. The idea is that all metrics (cpu, memory .. ) from all pods are gathered by Prometheus all you have to do is to find cpu metrics belonging to pods of sts 'master' then set up this metric for 'members'.  It's not trivial since you have to deploy Prometheus, Kube-metrics-adapter, you can find more info about using Prometheus custom metrics for HPA in this blog: https://banzaicloud.com/blog/k8s-hpa-prom-istio/. It's using Istion metrics as an example but of course you can use any other metric from Prometheus like cpu metrics.

**Comment by rimusz** [comment]
Yes, I know about the custom metrics way to be used for the second set of `sts`, doing it via controller makes more sense, and is more flexible.
